# Generated by Django 4.0.6 on 2024-09-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileForProccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(unique=True, verbose_name='Filename')),
                ('file_id', models.CharField(max_length=36, unique=True, verbose_name='FileID')),
                ('is_ready', models.BooleanField(default=False, verbose_name='IsReady')),
                ('lang', models.CharField(default='RUS', max_length=3, verbose_name='Language')),
                ('upload_time', models.DateTimeField(verbose_name='Date-Time')),
            ],
        ),
    ]
