# Generated by Django 4.0.6 on 2024-09-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileforproccess',
            name='has_toc_hint',
            field=models.BooleanField(blank=True, null=True, verbose_name='HasTOC'),
        ),
        migrations.AddField(
            model_name='fileforproccess',
            name='toc_end_hint',
            field=models.IntegerField(default=-1, verbose_name='EndTOC'),
        ),
        migrations.AddField(
            model_name='fileforproccess',
            name='toc_start_hint',
            field=models.IntegerField(default=-1, verbose_name='StartTOC'),
        ),
    ]
